### ISSUE TITLE
How do I batch if I have multiple .mviews files?

### ISSUE THREAD

**Issue by zhubenjie** [majimboo/mviewer#11]
100+ mview files

**Comment by majimboo** [comment]
If you are using Noesis it has a batch process feature. Use that one.

**Comment by majimboo** [comment]
Follow-up: the current 2.x workflow is different from the original scripts.

For current usage, including the command-line workflow, please see the README:
https://github.com/majimboo/mviewer#readme

Latest download:
https://github.com/majimboo/mviewer/releases/latest
