### ISSUE TITLE
'extract.bat' and 'Noesis' export files are not the same

### ISSUE THREAD

**Issue by zhubenjie** [majimboo/mviewer#13]
extract.bat:
```js
sometimes missing 'obj' file
```
Noesis:
```js
missing 'mtl' file
```

**Comment by majimboo** [comment]
Follow-up: this difference belonged to the old extract.bat/Noesis workflow.

The current 2.x version uses a single Rust-native export path instead of those separate legacy paths, and it now supports animation too.

Latest release:
https://github.com/majimboo/mviewer/releases/latest
