### ISSUE TITLE
Where does the generated obj get stored?

### ISSUE THREAD

**Issue by GMSyrimis** [majimboo/mviewer#2]
Maybe a silly question, but where's the final obj stored? I noticed I have an obj for each .dat file. I'm going to try and load each of them but it would be nice to have that included in the README.md

**Comment by cronos45** [comment]
Did you get it?

**Comment by majimboo** [comment]
Follow-up: the old workflow has been replaced.

In the current 2.x version, the exporter writes to the output directory you pass on the command line. For current usage, please see the README:
https://github.com/majimboo/mviewer#readme

Latest download:
https://github.com/majimboo/mviewer/releases/latest
